language: node_js

node_js:
  - '8'

sudo: enabled

notifications:
  email: false

before_install:
  - npm update

install:
  - npm install

script:
  - jest --clearCache --updateSnapshot --update
  - npm test
  - npm run coveralls

cache:
  directories:
    - node_modules
