language: node_js

node_js:
  - v10.14.1

sudo: enabled

install:
  - npm install

notifications:
  email: false

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: npm test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage